---
apiVersion: v1
kind: Namespace
metadata:
  name: rpc-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpc-app-deployment
  namespace: rpc-app
spec:
  selector:
    matchLabels:
      app: rpc-app
  replicas: 2
  template:
    metadata:
      labels:
        app: rpc-app
    spec:
      containers:
      - name: rpc-app-cont
        image: supergiantkir/prometheus-test-app
        ports:
        - name: web
          containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: rpc-app-service
  namespace: rpc-app
  labels:
    app: rpc-app
spec:
  ports:
  - name: web
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: rpc-app
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rpc-app
  namespace: rpc-app
  labels:
    env: rpc-app
spec:
  selector:
    matchLabels:
      app: rpc-app
  endpoints:
  - port: web
  namespaceSelector:
    matchNames:
      - default
      - rpc-app
      - monitoring
