scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jrmanes'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8081']
